language: python

dist: focal

python:
  - "3.9"

install:
  - make poetry
  - source $HOME/.poetry/env
  - make install

script:
  - make tests

after_success:
  - make cov-reports && poetry run codecov
